/**
 * FOREST-V2-A34 Sky Dome — PHASE 3 P3D (2026-05-17)
 *
 * Large inverted sphere (r=300, BackSide) painted with a per-phase vertical
 * gradient texture. Crossfades between phases over 3s using a ShaderMaterial
 * with two sampler2D uniforms (currentSky, nextSky) and a u_blend scalar.
 *
 * Phase detection: NO touch to src/forestDayNight.js per the contract — we
 * recompute the phase index here against the same thresholds (0/600/1200/
 * 1740/1800s) and the same _phaseAt() shape. If forestDayNight ever moves
 * those thresholds, mirror them here (single source of truth ideally; today
 * both modules duplicate the constants, documented at both call sites).
 *
 * Crossfade strategy (uniform swap, NOT material recompile):
 *   On phase change:
 *     u_next   ← new phase's texture
 *     u_blend  ← 0
 *     animate u_blend 0 → 1 over 3s
 *   On animation complete:
 *     u_current ← u_next        (the texture ref the shader has held)
 *     u_blend   ← 0             (back to "show current" only)
 *
 * One material, one geometry — recompile cost is zero across phases.
 *
 * Asset gate: the 5 sky textures are loaded synchronously via TextureLoader
 * (each loads async under the hood; we don't await onLoad — the shader
 * samples the bound texture even if its image hasn't decoded, which yields
 * a black sky for ~1 frame on first load). The asset budget is <3KB total,
 * so decode is essentially instant. No async gate.
 *
 * Initial-phase snap: first tick after load() does NOT crossfade; it snaps
 * u_current to whichever phase state.time.game resolves to. This handles
 * the resume-mid-run case (e.g. retry with time.game already past 1800s).
 * Documented + tested by the smoke phase 3 (time-jump to 700s on a fresh
 * load picks GOLDEN immediately).
 *
 * sRGB + tone mapping: textures bound with `colorSpace = SRGBColorSpace`.
 * ShaderMaterial does not auto-apply tone mapping (`material.toneMapped`
 * is read by the renderer for built-in materials only), but it also does
 * not double-apply sRGB — texelToLinear is wrapped into texture2D() by
 * the patch the renderer injects when colorSpace is set. To be safe we
 * call `outputColorSpace`-aware encoding inside the fragment shader and
 * trust the renderer's auto-replacement (`#include <encodings_pars_fragment>`
 * style). Postfx bloom should NOT pop the sky since renderOrder=-100 and
 * the sky doesn't hit BLOOM_LAYER.
 *
 * Z-order: renderOrder = -100, depthWrite = false, depthTest = true,
 * side = BackSide. Behind everything; fog (cohort 9) keeps applying to all
 * scene geometry INSIDE the dome at normal range so the sky shows beyond
 * the fog horizon naturally.
 *
 * Lifecycle:
 *   loadForestSkyDome(scene, state)  — idempotent; bails if already loaded.
 *   tickForestSkyDome(state, dt)     — detect phase, drive crossfade.
 *   disposeForestSkyDome(scene)      — remove dome, dispose geometry +
 *                                       material + textures. Idempotent.
 *
 * Mirrors the load-once-per-scene gating pattern of src/forestDayNight.js
 * (state._dayNightLoaded). The brief defines state._skyDomeLoaded.
 */

import * as THREE from 'three';

// ── Phase thresholds (MIRROR src/forestDayNight.js — DO NOT IMPORT) ────────
// Brief explicitly forbids touching forestDayNight; the threshold constants
// below are duplicated by design with a pointer-comment to the canonical
// source. If forestDayNight changes these, update them here in lockstep.
const T_MIDDAY_END   = 600;   // 0..600
const T_GOLDEN_END   = 1200;  // 600..1200
const T_DUSK_END     = 1740;  // 1200..1740
const T_TWILIGHT_END = 1800;  // 1740..1800; 1800+ = BLOOD_MOON

// Phase indices — also mirror forestDayNight.js (P_MIDDAY..P_BLOOD_MOON).
const P_MIDDAY     = 0;
const P_GOLDEN     = 1;
const P_DUSK       = 2;
const P_TWILIGHT   = 3;
const P_BLOOD_MOON = 4;
const PHASE_COUNT  = 5;

// Texture filename per phase index. Pre-generated by
// tools/_gen_sky_textures.mjs (assets/textures/sky_<phase>.png).
const SKY_FILES = [
  'assets/textures/sky_midday.png',
  'assets/textures/sky_golden.png',
  'assets/textures/sky_dusk.png',
  'assets/textures/sky_twilight.png',
  'assets/textures/sky_bloodmoon.png',
];

// Geometry tuning. r=300 wraps the playable 60u arena and the cohort 9 fog
// ramp comfortably without clipping the camera near-plane. 32×16 segments
// is plenty for a smooth gradient (no per-vertex variation — gradient lives
// in the texture).
const DOME_RADIUS    = 300;
const DOME_WIDTH_SEG = 32;
const DOME_HEIGHT_SEG = 16;

// Crossfade timing. 3s matches the cohort 9 ambient feel.
const CROSSFADE_DUR = 3.0;

// ── Module state ───────────────────────────────────────────────────────────
let _loaded     = false;
let _scene      = null;
let _mesh       = null;
let _geometry   = null;
let _material   = null;
let _textures   = null;   // Array<THREE.Texture> indexed by phase

let _currentPhase = -1;   // last phase shown by u_current
let _nextPhase    = -1;   // phase loaded into u_next during crossfade
let _blendT       = 0;    // 0..CROSSFADE_DUR — drives u_blend = _blendT / CROSSFADE_DUR
let _crossfading  = false;

// ── Shader (vertex / fragment) ─────────────────────────────────────────────
// vert: pass through UV. position is already the inverted sphere geometry.
const VERT = /* glsl */`
varying vec2 vUv;
void main() {
  vUv = uv;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`;

// frag: sample both sky textures, lerp by u_blend, output. THREE auto-injects
// sRGB→linear decode into texture2D() when the bound texture has
// colorSpace = SRGBColorSpace (renderer.outputColorSpace handles the encode
// on the final write to the framebuffer). We do NOT include tone-mapping
// chunks here — sky should bypass tone-mapping for color fidelity to the
// palette. Postfx bloom pass keys off BLOOM_LAYER, which we don't enable on
// the dome.
const FRAG = /* glsl */`
uniform sampler2D u_current;
uniform sampler2D u_next;
uniform float u_blend;
varying vec2 vUv;
void main() {
  vec4 cCur  = texture2D(u_current, vUv);
  vec4 cNext = texture2D(u_next,    vUv);
  vec3 rgb = mix(cCur.rgb, cNext.rgb, clamp(u_blend, 0.0, 1.0));
  gl_FragColor = vec4(rgb, 1.0);
}
`;

// ── Helpers ────────────────────────────────────────────────────────────────

/** Replicate src/forestDayNight.js::_phaseAt — index only, no t needed. */
function _phaseAt(gameT) {
  if (gameT < T_MIDDAY_END)   return P_MIDDAY;
  if (gameT < T_GOLDEN_END)   return P_GOLDEN;
  if (gameT < T_DUSK_END)     return P_DUSK;
  if (gameT < T_TWILIGHT_END) return P_TWILIGHT;
  return P_BLOOD_MOON;
}

/** Configure a freshly-loaded sky texture with palette-true sampling. */
function _prepTex(tex) {
  // Vertical gradients only — no tiling. ClampToEdge prevents seam artifacts
  // at the sphere pole + horizon ring.
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.wrapT = THREE.ClampToEdgeWrapping;
  // Linear filtering both min + mag for smooth gradient interpolation.
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  // No mipmaps needed (LinearFilter without mipmaps avoids the chain alloc).
  tex.generateMipmaps = false;
  // sRGB color space so palette hexes round-trip true through the shader.
  tex.colorSpace = THREE.SRGBColorSpace;
  // Anisotropy bumps oblique-angle sampling quality at the horizon ring.
  tex.anisotropy = 8;
  tex.needsUpdate = true;
  return tex;
}

/** Load all 5 sky textures eagerly. ~3 KB total — async decode is trivial. */
function _loadSkyTextures() {
  const loader = new THREE.TextureLoader();
  const out = new Array(PHASE_COUNT);
  for (let i = 0; i < PHASE_COUNT; i++) {
    const tex = loader.load(SKY_FILES[i], (t) => _prepTex(t));
    // The onLoad callback runs after decode, but `tex` is the same object;
    // applying _prepTex synchronously too ensures the wrap/filter state is
    // present even if the renderer samples the texture before decode (which
    // returns black until ready — harmless for the dome).
    _prepTex(tex);
    out[i] = tex;
  }
  return out;
}

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Once-per-scene init. Mounts the sphere mesh at scene root. Idempotent —
 * subsequent calls without an intervening dispose() bail.
 *
 * @param {THREE.Scene} scene
 * @param {object} _state — kept for API symmetry; first tick snaps phase
 *                          from state.time.game.
 */
export function loadForestSkyDome(scene, _state) {
  if (_loaded) return;
  if (!scene) return;
  _scene = scene;

  // ── Textures ─────────────────────────────────────────────────────────────
  _textures = _loadSkyTextures();

  // ── Geometry: inverted sphere via BackSide (cheaper than scale(-1,1,1)). ─
  _geometry = new THREE.SphereGeometry(DOME_RADIUS, DOME_WIDTH_SEG, DOME_HEIGHT_SEG);

  // ── Material: ShaderMaterial with two-sampler crossfade ─────────────────
  // Initialize both samplers to the midday texture; tickForestSkyDome's
  // first call snaps u_current to the resolved phase.
  _material = new THREE.ShaderMaterial({
    uniforms: {
      u_current: { value: _textures[P_MIDDAY] },
      u_next:    { value: _textures[P_MIDDAY] },
      u_blend:   { value: 0 },
    },
    vertexShader: VERT,
    fragmentShader: FRAG,
    side: THREE.BackSide,
    depthWrite: false,
    depthTest: true,
    fog: false,      // sky must not be fogged
    transparent: false,
    toneMapped: false, // ShaderMaterial: explicit pass-through
  });

  // ── Mesh ────────────────────────────────────────────────────────────────
  _mesh = new THREE.Mesh(_geometry, _material);
  _mesh.name = 'forestSkyDome';
  _mesh.renderOrder = -100;
  _mesh.frustumCulled = false; // always render — dome wraps the camera
  // No shadow casting / receiving on the sky.
  _mesh.castShadow = false;
  _mesh.receiveShadow = false;
  scene.add(_mesh);

  _currentPhase = -1;
  _nextPhase    = -1;
  _blendT       = 0;
  _crossfading  = false;
  _loaded       = true;
}

/**
 * Per-frame tick. Detects phase index from state.time.game; on a phase
 * change starts (or extends) a 3s crossfade to the new phase. On the
 * very first tick after load() the phase is SNAPPED (no animation) so
 * resume-mid-run lands on the correct sky immediately.
 *
 * @param {object} state
 * @param {number} dt  — real-frame dt (seconds). NOT game-time delta; we
 *                       want the crossfade to feel smooth even during
 *                       hit-stop / pause-for-life moments.
 */
export function tickForestSkyDome(state, dt) {
  if (!_loaded) return;
  if (!state) return;

  const gameT = (state.time && typeof state.time.game === 'number')
    ? state.time.game
    : 0;
  const phase = _phaseAt(gameT);

  // ── First tick after load: SNAP to current phase ────────────────────────
  if (_currentPhase === -1) {
    _currentPhase = phase;
    _nextPhase    = phase;
    _material.uniforms.u_current.value = _textures[phase];
    _material.uniforms.u_next.value    = _textures[phase];
    _material.uniforms.u_blend.value   = 0;
    _crossfading = false;
    _blendT = 0;
    return;
  }

  // ── Phase change while NOT crossfading: start a fresh fade ──────────────
  if (!_crossfading && phase !== _currentPhase) {
    _nextPhase = phase;
    _material.uniforms.u_next.value = _textures[phase];
    _material.uniforms.u_blend.value = 0;
    _blendT = 0;
    _crossfading = true;
    return;
  }

  // ── Phase change DURING an in-flight crossfade: hijack the target ───────
  // (rare — only if game-time scrubs past two phase boundaries in <3s, which
  // the smoke does via direct mutation of state.time.game). We immediately
  // settle the old fade by promoting u_current to u_next, then start a new
  // fade toward the latest phase. This avoids a visible "snap" mid-fade.
  if (_crossfading && phase !== _nextPhase && phase !== _currentPhase) {
    // settle in-flight
    _material.uniforms.u_current.value = _textures[_nextPhase];
    _currentPhase = _nextPhase;
    // start new
    _nextPhase = phase;
    _material.uniforms.u_next.value = _textures[phase];
    _material.uniforms.u_blend.value = 0;
    _blendT = 0;
    return;
  }

  // ── Advance the crossfade ──────────────────────────────────────────────
  if (_crossfading) {
    _blendT += (typeof dt === 'number' && dt > 0) ? dt : 0;
    if (_blendT >= CROSSFADE_DUR) {
      // Fade complete — promote u_next to u_current and reset blend.
      _material.uniforms.u_current.value = _textures[_nextPhase];
      _material.uniforms.u_blend.value = 0;
      _currentPhase = _nextPhase;
      _crossfading = false;
      _blendT = 0;
    } else {
      _material.uniforms.u_blend.value = _blendT / CROSSFADE_DUR;
    }
  }
}

/**
 * Tear down. Removes the mesh from the scene and disposes the geometry,
 * material, and all 5 textures. Idempotent — safe to call when never loaded.
 *
 * @param {THREE.Scene} [scene] — optional; falls back to cached _scene.
 */
export function disposeForestSkyDome(scene) {
  const targetScene = scene || _scene;
  if (_mesh && targetScene) {
    targetScene.remove(_mesh);
  }
  if (_geometry) {
    _geometry.dispose();
  }
  if (_material) {
    _material.dispose();
  }
  if (_textures) {
    for (const t of _textures) {
      if (t && typeof t.dispose === 'function') t.dispose();
    }
  }
  _mesh = null;
  _geometry = null;
  _material = null;
  _textures = null;
  _scene = null;
  _loaded = false;
  _currentPhase = -1;
  _nextPhase = -1;
  _blendT = 0;
  _crossfading = false;
}
